StarTEDSolution/Pages/Deliverables/CRUD.cshtml.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using StarTEDSolution.Helpers;
using StarTEDSystem.BLL;
using StarTEDSystem.Entities;

namespace StarTEDSolution.Pages.Deliverables
{
    public class CRUDModel : PageModel
    {
        #region Private service fields & class constructor
        private readonly ILogger<IndexModel> _logger;
        private readonly EmployeeServices _employeeServices;
        private readonly ProgramServices _programServices;
        private readonly PositionServices _positionServices;

        public CRUDModel(ILogger<IndexModel> logger,
                                            EmployeeServices employeeServices,
                                            ProgramServices programServices,
                                            PositionServices positionServices)
        {
            _logger = logger;
            _employeeServices = employeeServices;
            _positionServices = positionServices;
            _programServices = programServices;
        }
        #endregion

        [TempData]
        public string Feedback { get; set; }

        public bool HasFeedback => !string.IsNullOrWhiteSpace(Feedback);

        public string ErrorMessage { get; set; }

        public bool HasError => !string.IsNullOrWhiteSpace(ErrorMessage);

        [BindProperty(SupportsGet = true)]

        public int? employeeid { get; set; }

        [BindProperty(SupportsGet = true)]
        public string SearchArg { get; set; }

        [BindProperty]

        public Employee EmployeeInfo { get; set; }

        [BindProperty]
        public StarTEDSystem.Entities.Programs ProgramInfo { get; set; }

        [BindProperty]

        public List<StarTEDSystem.Entities.Programs> ProgramList { get; set; }  

        [BindProperty]

        public Position PositionInfo { get; set; }

        [BindProperty]

        public List <Position> PositionList { get; set; }

        #region Paginator
        //  Desired page size
        private const int PAGE_SIZE = 25;
        //  Hold an instance of the Paginator
        public Paginator Pager { get; set; }
        #endregion  


        public void OnGet()
        {

            PopulateLists(); 

            if (employeeid.HasValue && employeeid > 0)
            {
             
                EmployeeInfo = _employeeServices.GetByID(employeeid.Value);

                       
            }


        }

        public void PopulateLists()
        {
            ProgramList = _programServices.Program_List();
            PositionList = _positionServices.Position_List();
        }



        public IActionResult OnPostCancel()
        {
            Feedback = "Employee Table Information will be cleared and you will be returned to the Query page.";

            return RedirectToPage("/Deliverables/Query");


        }

        public IActionResult OnPostNew()
        {
            if (ModelState.IsValid)
            {
                try
                {
                  
                    int newemployeeID = _employeeServices.Employee_AddEmployee(EmployeeInfo);
                    
                    Feedback = $"Employee ({newemployeeID}) has been added to the system";
                    return RedirectToPage(new { employeeid = newemployeeID });

                }
                catch (ArgumentNullException ex)
                {
                    ErrorMessage = GetInnerException(ex).Message;
                  
                    PopulateLists();
                   
                    return Page();
                }
                catch (Exception ex)
                {
                    ErrorMessage = GetInnerException(ex).Message;
                    PopulateLists();
                    return Page();
                }
            }

            return Page();
        }

        public IActionResult OnPostDelete()
        {
            if (ModelState.IsValid)
            {
                try
                {
                    int employeeid = _employeeServices.Employee_DeleteEmployee(EmployeeInfo);
                    if (employeeid > 0)
                    {
                        Feedback = $" The new Employee Record ({employeeid}) was successfully created.";
                    }
                    else
                    {
                        Feedback = "No Employee was affected.  Refresh search and try again.";
                    }
                    return RedirectToPage(new { employeeid = employeeid });
                }
                catch (ArgumentNullException ex)
                {
                    ErrorMessage = GetInnerException(ex).Message;
                    PopulateLists();
                    return Page();
                }
                catch (Exception ex)
                {
                    ErrorMessage = GetInnerException(ex).Message;
                    PopulateLists();
                    return Page();
                }
            }

            return Page();
        }

        public IActionResult OnPostUpdate()
        {
            if (ModelState.IsValid)
            {
                try
                {
                    int employeeid = _employeeServices.Employee_UpdateEmployee(EmployeeInfo);
                    if (employeeid > 0)
                    {
                        Feedback = $"The Employee Record ({employeeid}) was successfully updated..";
                    }
                    else
                    {
                        Feedback = "No Employee Record was affected.  Refresh search and try again.";
                    }
                    return RedirectToPage(new { employeeid = employeeid });
                }
                catch (ArgumentNullException ex)
                {
                    ErrorMessage = GetInnerException(ex).Message;
                    PopulateLists();
                    return Page();
                }
                catch (Exception ex)
                {
                    ErrorMessage = GetInnerException(ex).Message;
                    PopulateLists();
                    return Page();
                }

                
            }
            return Page();
        }
        private Exception GetInnerException(Exception ex)
        {

            while (ex.InnerException != null)
            {
                ex = ex.InnerException;

            }
            return ex;
        }
    }
}

StarTEDSolution/Pages/Deliverables/Query.cshtml.cs
#nullable disable
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using System.Drawing;
using StarTEDSystem.BLL;
using StarTEDSystem.Entities;
using StarTEDSolution.Helpers;

namespace StarTEDSolution.Pages.Deliverables
{
    public class QueryModel : PageModel
    {
        #region Private service fields & class constructor
        private readonly ILogger<IndexModel> _logger;
        private readonly EmployeeServices _employeeServices;
        private readonly ProgramServices _programServices;
        private readonly PositionServices _positionServices;
  
        public QueryModel (ILogger<IndexModel> logger,
                                            EmployeeServices employeeServices,
                                            ProgramServices programServices,
                                            PositionServices positionServices)
        {
            _logger = logger;
            _employeeServices = employeeServices;
            _positionServices = positionServices;   
            _programServices = programServices;
        }
        #endregion

        [TempData]
        public string Feedback { get; set; }

        [BindProperty(SupportsGet = true)]
        public int EmployeeID { get; set; }

        [BindProperty(SupportsGet = true)]
        public string SearchArg { get; set; }

        [BindProperty]

        public List<Employee> EmployeeInfo { get; set; }

        [BindProperty]
        public List <StarTEDSystem.Entities.Programs> ProgramInfo { get; set; }

        [BindProperty]

        public List<Position> PositionInfo { get; set; }

        #region Paginator
        //  Desired page size
        private const int PAGE_SIZE = 25;
        //  Hold an instance of the Paginator
        public Paginator Pager { get; set; }
        #endregion


        public void OnGet(int? currentPage)
        {
            

            ProgramInfo = _programServices.Program_List();

            PositionInfo = _positionServices.Position_List();

            if (!string.IsNullOrWhiteSpace(SearchArg))
            {
                //  Setting up for using the Paginator only needs to be done if 
                //      a query is executing

                //  determine the current page number
                int pageNumber = currentPage.HasValue ? currentPage.Value : 1;

                //  Setup the current state of the pagomatpr (sizing)
                PageState current = new(pageNumber, PAGE_SIZE);

                //  Temporary local integer to hold the results of the query's total collection size
                //  This will be need by the Paginator during the paginator's execute
                int totalCount;

                EmployeeInfo = _employeeServices.GetByPartialName(SearchArg,
                                            pageNumber, PAGE_SIZE, out totalCount);
                Pager = new Paginator(totalCount, current);
            }

        }

        public IActionResult OnPostSearch()
        {
            

            if (string.IsNullOrWhiteSpace(SearchArg))
            {
                Feedback = "Required:  Search argument is empty";
            }
            return RedirectToPage(new { SearchArg = SearchArg });
        }

        public IActionResult OnPostClear()
        {
            Feedback = "Search results will be cleared..";
            
            ModelState.Clear();
            return RedirectToPage(new { SearchArg = (string?)null });
        }

        
        
    }
}

StarTEDSolution/Pages/Deliverables/CRUD.cshtml
@page "{EmployeeID?}"
@model StarTEDSolution.Pages.Deliverables.CRUDModel
@{
    ViewData["Title"] = "CRUD page";
}
<div class="text-center">
    <h1 class="display-4">This is the CRUD Page!</h1>
    <a asp-area="" asp-page="/CRUD"></a>
    <img src="~/img/CRUDImage.jpg" alt="" title="" />
    </div>

<h1>Employees by Partial Name</h1>

<style>
    :root {
        --max-body-width: 60rem;
    }

    .setflex {
        display: flex;
    }

    .onethird {
        width: 31%;
        margin-right: 2%;
    }

    .onehalf {
        width: 47%;
        margin-right: 3%;
    }

    .smallbox {
        width: 60px;
    }

</style>

@if (Model.HasFeedback)
{
    <p>@Model.Feedback</p>
}
@if (Model.HasError)
{
    <p>@Model.ErrorMessage</p>
}

<form method="post">

    <label>
        Employee ID:
        <input type="text" asp-for="EmployeeInfo.FullName" readonly data-val="false" />
        <span asp-validation-for="EmployeeInfo.FirstName"></span>
    </label>

    <label>
        Position:
        <select asp-for="PositionInfo.Description">
            @foreach (var item in Model.PositionList)
            {
                <option value="@item.Description"
                    selected=@(Model.PositionInfo != null && item.Description == Model.PositionInfo.Description)>
                    @item.Description
                </option>
            }
        </select>
    </label>
    
    <label>
        Program:
        <select asp-for="ProgramInfo.ProgramName">
            @foreach (var item in Model.ProgramList)
            {
                <option value="@item.ProgramName"
                    selected=@(Model.PositionInfo != null && item.ProgramName == Model.ProgramInfo.ProgramName)>
                    @item.ProgramName
                </option>
            }
        </select>
    </label>
    <label>
        ReleaseDate: 
        <input type="date" asp-for="EmployeeInfo.ReleaseDate" placeholder="Date" />
        <span asp-validation-for="EmployeeInfo.ReleaseDate"></span>
    </label>
  
    <br /><br />
    @* Managing the buttons, restricting user access*@
    @if (Model.EmployeeInfo != null)
    {
        <button type="submit" asp-page-handler="New" disabled>New</button>
        <button type="submit" asp-page-handler="Update">Update</button>
        @* add Javascript prompt for delete confirmation using the onclick *@
        <button type="submit" asp-page-handler="Delete" formnovalidate
            onclick="return confirm('Are you sure you wish to delete the current information? Employee is not to be deleted.')">
            Delete
        </button>
    }
    else
    {
        <button type="submit" asp-page-handler="New">New</button>
        <button type="submit" asp-page-handler="Update" disabled>Update</button>
        @* add Javascript prompt for delete confirmation using the onclick *@
        <button type="submit" asp-page-handler="Delete" formnovalidate 
            onclick="return confirm('Are you sure you wish to delete the Rolling Stock?')">
            Delete
        </button>
    }
    <button type="submit" asp-page-handler="Cancel" formnovalidate>Cancel</button>
</form>

@section scripts{
    <partial name="_ValidationScriptsPartial" />
        }

        @*

  @if (Model.EmployeeInfo != null)
    {
        if (Model.EmployeeInfo.Count() == 0)
        {
            <p style="color: red; font-weight: bold; font-size: large">
                There are no Employees matching your search request
            </p>
        }
        else
        {
            <table>
                <thead>
                    <tr>
                        <th></th>
                        <th>Name</th>
                        <th>Position</th>
                        <th>Program</th>
                    </tr>
                </thead>
                  <tbody>

                    @foreach (var item in Model.EmployeeInfo)
                    {
                        <tr>

                            <td>
                                <a href="/Deliverables/CRUD/@item.EmployeeID">
                                    Edit 
                                </a>
                            </td>

                            <td>@item.LastName, @item.FirstName</td>
                            
                         
                            <td>
                            <select>
                                    @foreach (var position in Model.PositionInfo)
                                    {
                                            if (position.Description == position.Description)
                                        {
                                            <option value="@position.Description " selected>@position.Description </option>
                                        }
                                        else
                                        {
                                            <option value="@position.Description">@position.Description </option>
                                        }
                                    }
                            </select>
                            </td>

                            
                                
                          
                         
                            <td>
                            <select>
                                    @foreach (var programs in Model.ProgramInfo)
                                    {
                                            if (programs.ProgramName == programs.ProgramName)
                                        {
                                            <option value="Programs.ProgramID " selected>@programs.ProgramName </option>
                                        }
                                        else
                                        {
                                             <option value="@programs.ProgramName ">@programs.ProgramName </option>
                                        }
                                    }
                            </select>
                            </td>
                            
                        </tr>
                    }
                 </tbody>

              
                    
            </table>

            *@
    
        
    

StarTEDSolution/Pages/Deliverables/Query.cshtml
@page "{SearchArg?}/{EmployeeID?}"
@model StarTEDSolution.Pages.Deliverables.QueryModel
@{
    ViewData["Title"] = "Query";
}

<div class="text-center">
    <h1 class="display-4">This is the Query Page!!!</h1>
    <a asp-area="" asp-page="/Query"></a>
    <img src="~/img/A01Mockup.png" alt="" title="" />
    <p>The purpose of this page is to generate and display the results of searching the database of Employees by a partial name. Specifically for the database's "active Employees". This must be possible by Firstname and Lastname search queries. It will function as a drop down display, and the results will appear in alphabetic order. The display must include the fullname, program and position data. As well as options to clear the entered search, a paginator for page selecting and drop-down menus to navigate the position and programs data within the search results. </p>
</div>

<h1>Employees by Partial Name</h1>
<form method="post">

 
    <label>
        Enter a partial name
        <input type="text" asp-for="SearchArg"
               placeholder="Enter the partial employee name" required />
    </label>
    <br />

        <button type="submit" asp-page-handler="Search">Search</button>
        <button type="submit" asp-page-handler="Clear" formnovalidate>Clear</button>

    @if (Model.EmployeeInfo != null)
    {
        if (Model.EmployeeInfo.Count() == 0)
        {
            <p style="color: red; font-weight: bold; font-size: large">
                There are no Employees matching your search request
            </p>
        }
        else
        {
            <table>
                <thead>
                    <tr>
                        <th></th>
                        <th>Name</th>
                        <th>Position</th>
                        <th>Program</th>
                    </tr>
                </thead>
                  <tbody>

                    @foreach (var item in Model.EmployeeInfo)
                    {
                        <tr>

                            <td>
                                <a href="/Deliverables/CRUD/@item.EmployeeID">
                                    Edit 
                                </a>
                            </td>

                            <td>@item.LastName, @item.FirstName</td>
                            
                         
                            <td>
                            <select>
                                    @foreach (var position in Model.PositionInfo)
                                    {
                                            if (position.Description == position.Description)
                                        {
                                            <option value="@position.Description " selected>@position.Description </option>
                                        }
                                        else
                                        {
                                            <option value="@position.Description">@position.Description </option>
                                        }
                                    }
                            </select>
                            </td>

                            
                                
                          
                         
                            <td>
                            <select>
                                    @foreach (var programs in Model.ProgramInfo)
                                    {
                                            if (programs.ProgramName == programs.ProgramName)
                                        {
                                            <option value="Programs.ProgramID " selected>@programs.ProgramName </option>
                                        }
                                        else
                                        {
                                             <option value="@programs.ProgramName ">@programs.ProgramName </option>
                                        }
                                    }
                            </select>
                            </td>
                            
                        </tr>
                    }
                 </tbody>

              
                    
            </table>

            <tfoot>
                @*  *** ERROR : "Title: Query - Object instance not set " *** *@
                <tr>
                    @{

                        foreach (var pageRef in Model.Pager)
                        {
                            if (pageRef == Model.Pager.CurrentPage)
                            {
                                <b>@pageRef.Text</b>
                            }
                            else
                            {

                                <a title="Page @pageRef.Page"
               asp-page="/Deliverables/Query"
               asp-route-currentpage="@pageRef.Page">
                                    @pageRef.Text
                                </a>
                            }
                        }
                    }
                </tr>
            </tfoot>
        }
    }
    
</form>